# Generated by Django 5.2 on 2025-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок записи в блоге",
                        max_length=150,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите содержимое записи в блоге",
                        null=True,
                        verbose_name="Содержимое записи",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для записи блога",
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Дата будет установлена автоматически при создании записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "viewed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Введите количество просмотров записи в блоге",
                        verbose_name="Количество просмотров",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, опубликована ли запись",
                        verbose_name="Флаг публикации записи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в блоге",
                "verbose_name_plural": "Записи в блоге",
            },
        ),
    ]
