# Generated by Django 5.2 on 2025-06-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта")
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если продукт опубликован",
                verbose_name="Статус публикации продукта",
            ),
        ),
    ]
